name: Deploy Release

on:
  push:
    branches:
      - master
      - release

env:
  RUST_VERSION: stable
  CARGO_INCREMENTAL: 0
  RUSTUP_MAX_RETRIES: 10
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: full
  BIN_NAME: spelli.exe

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Divvun CI
      uses: divvun/actions/setup@master
      with:
        key: ${{ secrets.DIVVUN_KEY }}
    - name: Get version
      uses: divvun/actions/version@develop
      with:
        cargo: true
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        target: i686-pc-windows-msvc
    - name: Build
      uses: actions-rs/cargo@v1
      env:
        RUSTC_BOOTSTRAP: 1
      with:
        command: build
        args: --release --target i686-pc-windows-msvc
        toolchain: stable
    - run: mkdir -p dist/bin
    - run: cp target/i686-pc-windows-msvc/release/${{ env.BIN_NAME }} dist/bin/${{ env.BIN_NAME }}
    - name: Codesign
      uses: divvun/actions/codesign@develop
      with:
        path: dist/bin/${{ env.BIN_NAME }}
    - name: Create tarball package
      uses: divvun/actions/create-txz@develop
      with:
        path: dist
