name: spelli

on:
  push:
    branches:
      - master
      - develop
      - release

env:
  RUST_VERSION: stable
  CARGO_INCREMENTAL: 0
  RUSTUP_MAX_RETRIES: 10
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: full
  BIN_NAME: spelli.exe

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Divvun CI
      uses: divvun/actions/setup@master
      with:
        key: ${{ secrets.DIVVUN_KEY }}
    - name: Get version
      id: version
      uses: divvun/actions/version@develop
      with:
        cargo: true
        nightly: master, develop
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install build dependencies
      uses: divvun/actions/pahkat/init@develop
      with:
        repo: https://pahkat.uit.no/devtools/
        channel: nightly
        packages: pahkat-uploader
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        target: i686-pc-windows-msvc
    - name: Build
      uses: actions-rs/cargo@v1
      env:
        RUSTC_BOOTSTRAP: 1
      with:
        command: build
        args: --release --target i686-pc-windows-msvc
        toolchain: stable
    - name: Create dist directory
      run: |
        mkdir -p dist/bin
        cp target/i686-pc-windows-msvc/release/${{ env.BIN_NAME }} dist/bin/${{ env.BIN_NAME }}
    - name: Sign code
      uses: divvun/actions/codesign@develop
      with:
        path: dist/bin/${{ env.BIN_NAME }}
    - name: Create tarball package
      id: tarball
      uses: divvun/actions/create-txz@develop
      with:
        path: dist
    - name: Deploy
      uses: divvun/actions/deploy@develop
      with:
        package-id: spelli
        platform: windows
        arch: i686
        type: TarballPackage
        version: ${{ steps.version.outputs.version }}
        payload-path: ${{ steps.tarball.outputs['txz-path'] }}
        repo: https://pahkat.thetc.se/devtools/
        channel: ${{ steps.version.outputs.channel }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

